services:
  - type: web
    name: bigbasket-panel-processor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
    plan: free
    healthCheckPath: /
    autoDeploy: true